version: '3'

services:
  blog-server:
    build: ./docker/php
    image: blog-symfony
    depends_on:
      - db
    volumes:
      - ./:/application:cached
      - /application/var/sessions/

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony-blog
    volumes:
      - ./tmp/db:/var/lib/mysql

  db-test:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony-blog-test
      MYSQL_USER: gandalf
      MYSQL_PASSWORD: secret_test
    volumes:
      - ./tmp/test:/var/lib/mysql

  nginx:
    image: nginx
    ports:
      - '8000:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application:cached
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - blog-server

  mercure:
    image: dunglas/mercure
    ports:
      - '9090:80'
    environment:
      - JWT_KEY=symfonyBlogJwtToken
      - ALLOW_ANONYMOUS=1
      - PUBLISH_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_ORIGINS=*
      - DEBUG=1
